name: CI/CD Pipeline

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        echo "${{ secrets.SSH_KEY }}" > DevOpsLabKey.pem
        chmod 600 DevOpsLabKey.pem

    - name: Add remote server to known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H 52.77.239.148 >> ~/.ssh/known_hosts

    - name: Debugging: List files on EC2
      run: |
        ssh -i DevOpsLabKey.pem ec2-user@52.77.239.148 'ls -l /home/ec2-user'

    - name: Deploy to server
      run: |
        ssh -i DevOpsLabKey.pem ec2-user@52.77.239.148 'cd /home/ec2-user && docker-compose up -d'
