name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger bila ada push ke branch `main`
  pull_request:
    branches:
      - main  # Trigger bila ada pull request ke branch `main`

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install SSH Client
        run: sudo apt-get update && sudo apt-get install -y openssh-client

      - name: Copy Docker Compose File to EC2
        run: |
          scp -i DevOpsLabKey.pem docker-compose.yml ec2-user@52.77.239.148:/home/ec2-user/seproject/

      - name: Deploy Application
        run: |
          ssh -i DevOpsLabKey.pem ec2-user@52.77.239.148 "
          cd /home/ec2-user/seproject &&
          docker-compose up -d
          "
