name: CI/CD Pipeline
•
• on:
• push:
• branches:
• - main
•
• jobs:
• build-and-deploy:
• runs-on: ubuntu-latest
•
• steps:
• - name: Checkout code
• uses: actions/checkout@v3
•
• - name: Set up Docker
• uses: docker/setup-buildx-action@v2
•
• - name: Build Docker image
• run: docker build -t your-dockerhub-username/devops-app .
•
• - name: Push to Docker Hub
• env:
• DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
• DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
• run: |
• echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --
password-stdin
• docker tag devops-app your-dockerhub-username/devopsapp:latest
• docker push your-dockerhub-username/devops-app:latest
•
• - name: Deploy to AWS EC2
• run: ssh -i your-key.pem ec2-user@your-ec2-ip \
• "docker pull your-dockerhub-username/devops-app:latest &&
docker run -d -p 3000:3000 your-dockerhub-username/devops-app:latest"